
FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY go-agent/. .
RUN go mod tidy && go mod download
RUN go build -v -o agent main.go


FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/agent .
EXPOSE 8001
CMD ["./agent"]
